#!/usr/bin/env python3
"""Bundle the project into one file another Claude can read.

Why a script rather than a written-once document: this thing changes. A
handoff that is regenerated in five seconds stays true; one that is written
by hand goes stale the first afternoon somebody works on the classifier.

What goes in, and why:

  CLAUDE.md        the complete current state - what exists, what is
                   measured, what is a dead end, what to do next.
  the decision log  every commit message, newest first. This is where the
                   REASONING lives: not just that the classifier trains on
                   human labels only, but that it used to train on its own
                   output and what that did to the DUBSTEP crate. A reader
                   who has this will not repeat the mistakes.
  the file map     what each file is for.
  the interfaces   every function signature with its docstring, so the shape
                   of the code is visible without shipping 250KB of it.

What stays out: the model weights (700KB of floats that mean nothing to a
reader), the audio, and the database. Those are not understanding, they are
payload.

Usage:
    python make_handoff.py            # writes HANDOFF.md
    python make_handoff.py --full     # also inlines every source file
"""
import argparse
import ast
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parent

SOURCE = [
    "analyze.py",
    "crateapp/db.py", "crateapp/scanner.py", "crateapp/worker.py",
    "crateapp/classifier.py", "crateapp/crates.py", "crateapp/runner.py",
    "crateapp/server.py", "crateapp/exporters.py", "crateapp/bootstrap.py",
    "crateapp/mixing.py", "crateapp/sets.py",
    "eval_genre.py", "tune_genre.py", "retrain.py",
    "groove_experiment.py", "house_vs_tech.py", "pooling_experiment.py",
    "mfcc_experiment.py",
]


def run(*args):
    try:
        return subprocess.run(args, cwd=ROOT, capture_output=True,
                              text=True, timeout=60).stdout.strip()
    except Exception:
        return ""


def interfaces(path):
    """Every public function and class in a file, with its docstring.

    The docstrings in this project carry the measurements and the reasons, so
    this is most of the value of the source at a fraction of the size.
    """
    try:
        tree = ast.parse((ROOT / path).read_text())
    except Exception:
        return ""
    out = []
    for node in tree.body:
        if isinstance(node, ast.ClassDef):
            doc = ast.get_docstring(node) or ""
            out.append(f"class {node.name}:\n    {doc}".rstrip())
            for sub in node.body:
                if isinstance(sub, (ast.FunctionDef, ast.AsyncFunctionDef)):
                    if sub.name.startswith("_") and sub.name != "__init__":
                        continue
                    sig = ast.unparse(sub.args)
                    sdoc = ast.get_docstring(sub) or ""
                    out.append(f"    def {sub.name}({sig}):\n        {sdoc}".rstrip())
        elif isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            if node.name.startswith("_"):
                continue
            sig = ast.unparse(node.args)
            doc = ast.get_docstring(node) or ""
            out.append(f"def {node.name}({sig}):\n    {doc}".rstrip())
    return "\n\n".join(out)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--full", action="store_true",
                    help="inline every source file as well")
    ap.add_argument("-o", "--out", default="HANDOFF.md")
    a = ap.parse_args()

    parts = []
    parts.append(
        "# Crate — complete handoff\n\n"
        "_Generated by `make_handoff.py`. Regenerate it rather than editing "
        "it by hand._\n\n"
        "This is a music-library sorting tool for a working DJ. Everything "
        "needed to understand the project is below: its current state, the "
        "reasoning behind every decision, and the measured dead ends that "
        "should not be retried.\n\n"
        "**Read section 1 first.** It is the project's own context file and "
        "it is kept current.\n\n---\n")

    parts.append("# 1. Project state (CLAUDE.md)\n\n"
                 + (ROOT / "CLAUDE.md").read_text())

    parts.append(
        "\n\n---\n\n# 2. Why everything is the way it is\n\n"
        "Every commit message, newest first. This is the reasoning behind the "
        "code: not just *what* was decided but *what went wrong first*. "
        "Several entries are corrections of earlier mistakes — those are the "
        "most useful ones.\n\n```\n"
        + run("git", "log", "--format=%h %ad%n%s%n%n%b%n"
                            "--------------------------------------------------",
              "--date=short")
        + "\n```\n")

    tree = run("git", "ls-files")
    parts.append("\n\n---\n\n# 3. What is in the repository\n\n```\n"
                 + tree + "\n```\n")

    parts.append(
        "\n\n---\n\n# 4. The interfaces\n\n"
        "Every public function, with its docstring. The docstrings carry the "
        "measurements and the reasons, so this is most of the value of the "
        "source at a fraction of its size.\n")
    for path in SOURCE:
        if not (ROOT / path).exists():
            continue
        body = interfaces(path)
        if body:
            parts.append(f"\n## `{path}`\n\n```python\n{body}\n```\n")

    if a.full:
        parts.append("\n\n---\n\n# 5. Full source\n")
        for path in SOURCE + ["crateapp/static/app.js", "crateapp/static/app.css"]:
            p = ROOT / path
            if not p.exists():
                continue
            lang = ("python" if p.suffix == ".py"
                    else "javascript" if p.suffix == ".js" else "css")
            parts.append(f"\n## `{path}`\n\n```{lang}\n{p.read_text()}\n```\n")

    parts.append(
        "\n\n---\n\n# Not included, on purpose\n\n"
        "- `crate_model.json` — 700KB of trained weights. Meaningless to read, "
        "and regenerated by `python retrain.py`.\n"
        "- `~/.crate/library.db` — the DJ's catalogue. Rebuilt by scanning "
        "their folders.\n"
        "- The audio itself, and `~/Documents/rek.xml` (their Rekordbox "
        "export, which is the ground truth the model learns from).\n\n"
        "A reader who wants to RUN this needs the repository, not this file. "
        "A reader who wants to UNDERSTAND it needs nothing else.\n")

    out = ROOT / a.out
    text = "\n".join(parts)
    out.write_text(text)
    print(f"{out}  ({len(text)/1024:.0f} KB)")


if __name__ == "__main__":
    main()
